### ISSUE TITLE
issue-14: Update Feature for Editor Component & Implemet Modal

### ISSUE THREAD

**Issue by gialynguyen** [gialynguyen/vcteam-homepage#35]
**1. File dir**:

      - src/components/Editor/*
      - src/components/Modal/*

**2. Todo**:
*2.1* Update Preview Mode (use Modal)
*2.2* Update Feature for Editor

- [x] onTab (tabSize = 4): support for creator
- [x] breakLine shortcut key: shift-enter

*2.3* Implement & Update Modal
- [x] onEseKey handle event
